### ISSUE TITLE
大佬你好，我在参考tls-bootstrapping时有一点疑问，为什么bootstrap.secret.yaml中相关配置和官方文档里的不一样，是有什么特别的原因吗呢？

### ISSUE THREAD

**Issue by wjtien** [cby-chen/Kubernetes#3]
官方文档：https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/
主要是 bootstrap.secret.yaml中的auth-extra-groups:  system:bootstrappers:default-node-token中为什么要额外加这个呢。。。
### 以及随后的绑定中的角色名也不一样了：
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-bootstrapper #这个角色不是system:bootstrappers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:bootstrappers:default-node-token #这里不是system:node-bootstrapper
```
